[package]
name = "proxy"
version = "0.1.0"
authors = ["Staś Małolepszy <stas@mozilla.com>"]
edition = "2018"

[dependencies]
corsware = "*"
hubcaps = "*"
iron = "*"
router = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
tokio = "*"
